version: "3.8"


x-environment: &envronment
  DB_CONNECTION: ${DB_CONNECTION}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  TZ: ${TZ}

services:
  db:
    container_name: postgresql
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    environment: *envronment
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
    tty: true

    

